---
app:
  id: mybot-1
  classpath:
    - ./custom

outputs:
#  console:
#    provider: outputs.ConsoleOutput
#  gelf:
#    provider: outputs.GelfOutput
#    gelf_host: localhost
#    gelf_port: 12201
#    gelf_protocol: udp
  rest:
    provider: custom.outputs.RestOutput
    #    silent: True
    contentType: text/html
    rest_host: https://status.hubbox.io/ping/9MEYvbOkoswk-reCK4fvrQ/{watcher_name}/{status-text}


triggers:
  each_1_minute:
    provider: triggers.SimpleTimer
    interval: 60

watchers:
#  system_time:
#    provider: watchers.SystemTimeWatcher
#    output: rest
#    triggers:
#      - each_1_minute
#    custom_assertions:
#      check_title:
#        provider: assertions.TitleAssert
#        expected_title: 'Google'

  machinemonitor-api:
    provider: watchers.HttpRequest
    url: http://blahblah123blah.com/
    assert_response_time: 2
    assert_status: 200
    triggers:
      - each_1_minute

#  google_home:
#    provider: watchers.HttpRequest
#    url: http://google.com
#    assert_response_time: 3
#    assert_status: 200
#    triggers:
#      - each_1_minute
#    custom_assertions:
#      check_title:
#        provider: assertions.TitleAssert
#        expected_title: 'Google'