---
app:
  id: mybot-1
  classpath:
    - ./custom

outputs:
  console:
    provider: outputs.ConsoleOutput
  gelf:
    provider: outputs.GelfOutput
    gelf_host: localhost
    gelf_port: 12201
    gelf_protocol: udp
  rest:
    provider: custom.outputs.RestOutput
    #    silent: True
    contentType: text/html
    rest_host: https://status.hubbox.io/ping/xxx/{watcher_name}


triggers:
  each_1_minute:
    provider: triggers.SimpleTimer
    interval: 60

watchers:
  system_time:
    provider: watchers.SystemTimeWatcher
    triggers:
      - each_1_minute

  dns_doesnt_exist:
    provider: watchers.HttpRequest
    url: http://blahblah123blah.com/
    assert_response_time: 2
    assert_status: 200
    output: rest
    triggers:
      - each_1_minute

  google_home:
    provider: watchers.HttpRequest
    url: http://google.com
    assert_response_time: 3
    assert_status: 200
    triggers:
      - each_1_minute
    custom_assertions:
      check_title:
        provider: assertions.TitleAssert
        expected_title: 'Google'